# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Did You Lift Today?
#email: your-email@domain.com
description: > 
  Do you lift? 
  Do you wish people asked you if you lift, just so you can say that you do? 
  Well now you can have your phone or tablet ask you, giving you that positive, self-righteous feeling as often as you want. 
  When you admit that you haven't actually lifted today, the app will help you find a nearby gym. 
  No excuses; lift like a champion.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://corb.co/lift" # the base hostname & protocol for your site
permalink: pretty # to remove the ".html" extension when serving file

# Limit what is hosted on the site.
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "README.md"]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
